window.EVENTS = [
  {date:'2026-08-29',time:'19:00',category:'Batismos',location:'Amaralina - Central',detail:'Ancião: Genivaldo Ferreira'},
  {date:'2026-08-09',time:'',category:'Viagens missionárias',location:'Campos Verdes - Central',detail:'Enc.: David Corrêa; Enc.: Manoel Messias'},
  {date:'2026-08-15',time:'19:00',category:'Reuniões para mocidade',location:'Santa Terezinha de Goiás - Central',detail:'Culto para jovens — Ancião: Ismael Zanelato'},
  {date:'2026-08-16',time:'09:00',category:'Ensaios regionais',location:'Alto Horizonte - Central',detail:'Anc.: Gideonir Teixeira; Enc.: Emanoel Siqueira; Enc.: Moyses Rosa'},
  {date:'2026-08-16',time:'14:00',category:'Reuniões para mocidade',location:'Alto Horizonte - Central',detail:'Ancião: Gideonir Teixeira'},
  {date:'2026-08-16',time:'19:00',category:'Batismos',location:'Crixás - Central',detail:'Ancião: Silvanio Machado'},
  {date:'2026-08-16',time:'19:00',category:'Batismos',location:'Santa Terezinha de Goiás - Central',detail:'Ancião: Ismael Zanelato'},
  {date:'2026-08-17',time:'19:30',category:'Reuniões diversas',location:'Niquelândia - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-20',time:'19:30',category:'Reuniões diversas',location:'Barro Alto - Vila Extrema',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-22',time:'',category:'Viagens missionárias',location:'Guarinos - Centro',detail:'Adm.: Grupo Engenharia Regional'},
  {date:'2026-08-23',time:'19:00',category:'Santas ceias',location:'Campos Verdes - Central',detail:'Ancião: Aurelino Santana'},
  {date:'2026-08-23',time:'19:00',category:'Santas ceias',location:'Crixás - Central',detail:'Ancião: Silvanio Machado'},
  {date:'2026-08-26',time:'19:30',category:'Reuniões para mocidade',location:'Nova Glória',detail:'Culto para jovens — Ancião: Luciano Pontes'},
  {date:'2026-08-26',time:'21:00',category:'Reuniões diversas',location:'Uruaçu - Central',detail:'Reunião Ministerial e Administrativa (RMA)'},
  {date:'2026-08-26',time:'',category:'Viagens missionárias',location:'Uruaçu - Central',detail:'Ancião: Cezar Francisco'},
  {date:'2026-08-27',time:'21:00',category:'Reuniões diversas',location:'Itapaci - Central',detail:'Reunião Ministerial Setor 2'},
  {date:'2026-08-28',time:'19:30',category:'Reuniões diversas',location:'Goianésia - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-30',time:'09:00',category:'Reuniões diversas',location:'Ceres - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-30',time:'14:00',category:'Reuniões diversas',location:'Rubiataba - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-30',time:'19:00',category:'Batismos',location:'Campinaçu - Central',detail:'Ancião: Cezar Francisco'},
  {date:'2026-08-30',time:'19:00',category:'Batismos',location:'Ceres - Central',detail:'Ancião: Elias França'},
  {date:'2026-08-30',time:'19:00',category:'Reuniões para mocidade',location:'Novo Planalto',detail:'Culto para jovens — Ancião: Moisés Eduardo'},
  {date:'2026-08-31',time:'19:00',category:'Reuniões diversas',location:'Carmo do Rio Verde - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-31',time:'19:00',category:'Reuniões diversas',location:'Porangatu - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-08-31',time:'19:30',category:'Reuniões diversas',location:'Campinorte - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-09-06',time:'15:00',category:'Reuniões diversas',location:'Carmo do Rio Verde - Central',detail:'Reunião com porteiros, operadores de som e irmãs auxiliares da porta'},
  {date:'2026-09-09',time:'',category:'Reuniões diversas',location:'Santa Terezinha de Goiás - Central',detail:'Reunião com ministério local'},
  {date:'2026-09-10',time:'',category:'Reuniões diversas',location:'Crixás - Central',detail:'Reunião Ministerial e Administrativa - RMA'},
  {date:'2026-09-12',time:'19:00',category:'Batismos',location:'Porangatu - Central',detail:'Ancião: Seir Borges'},
  {date:'2026-09-13',time:'09:00',category:'Reuniões diversas',location:'Uruaçu - Central',detail:'Reunião anual de ensinamentos da Obra da Piedade'},
  {date:'2026-09-13',time:'19:00',category:'Batismos',location:'Barro Alto - Souzalandia',detail:'Ancião: Douglas Vaz'},
  {date:'2026-09-13',time:'19:00',category:'Batismos',location:'Goianésia - Central',detail:'Ancião: Antônio Líbero'},
  {date:'2026-09-13',time:'19:00',category:'Batismos',location:'Minaçu - Central',detail:'Ancião: Valdivino Albino'},
  {date:'2026-09-13',time:'19:00',category:'Batismos',location:'Niquelândia - Central',detail:'Ancião: Vilmar Rodrigues'},
  {date:'2026-09-14',time:'19:30',category:'Reuniões diversas',location:'Online',detail:'Reunião de captação da Regional ADM (online)'},
  {date:'2026-09-19',time:'14:00',category:'Assuntos musicais',location:'Niquelândia - Central',detail:'Testes para músicos e organistas e exames de oficialização. Anc. Silvanio Machado; Encs. David Corrêa, Manoel Messias, João Batista; Exam. Krishna Silva, Lindalva de Paula, Abadia de Fátima'},
  {date:'2026-09-20',time:'09:00',category:'Ensaios regionais',location:'Niquelândia - Central',detail:'Anc.: Douglas Vaz; Enc.: Renato Santos; Enc.: Valteir Batista'},
  {date:'2026-09-20',time:'14:00',category:'Reuniões para mocidade',location:'Niquelândia - Central',detail:'Ancião: Douglas Vaz'},
  {date:'2026-09-20',time:'19:00',category:'Batismos',location:'Itapaci - Central',detail:'Ancião: Rafael dos Santos'},
  {date:'2026-09-20',time:'19:00',category:'Batismos',location:'Santa Terezinha de Goiás - Central',detail:'Ancião: Aurelino Santana'},
  {date:'2026-09-25',time:'',category:'Avisos à irmandade',location:'Todas as congregações da regional',detail:'Coleta especial para Anexo Uruaçu. Chave Pix: ccbanexo@gmail.com'},
  {date:'2026-09-26',time:'',category:'Avisos à irmandade',location:'Todas as congregações da regional',detail:'Coleta especial para Anexo Uruaçu. Chave Pix: ccbanexo@gmail.com'},
  {date:'2026-09-27',time:'09:00',category:'Reuniões diversas',location:'Online',detail:'Reunião de aconselhamento ao ministério - RAM. O link será disponibilizado para as administrações'},
  {date:'2026-09-27',time:'15:00',category:'Reuniões diversas',location:'Ceres - Central',detail:'Reunião com porteiros, operadores de som e irmãs auxiliares da porta'},
  {date:'2026-09-27',time:'',category:'Avisos à irmandade',location:'Todas as congregações da regional',detail:'Coleta especial para Anexo Uruaçu. Chave Pix: ccbanexo@gmail.com'},
  {date:'2026-10-09',time:'19:30',category:'Reuniões diversas',location:'Uruaçu - Central',detail:'Reunião com as coordenações da Regional Uruaçu'},
  {date:'2026-10-10',time:'08:00',category:'Avisos à irmandade',location:'Uruaçu - Central',detail:'Exames médicos para emissão de ASO — administrações de Ceres, Carmo do Rio Verde e Rubiataba'},
  {date:'2026-10-10',time:'08:30',category:'Reuniões diversas',location:'Uruaçu - Central',detail:'RRM - Reunião Regional Ministerial — anciães e diáconos'},
  {date:'2026-10-10',time:'10:00',category:'Reuniões diversas',location:'Uruaçu - Central',detail:'RRM - Reunião Regional Ministerial — anciães, diáconos, cooperadores e cooperadores de jovens e menores'},
  {date:'2026-10-11',time:'09:00',category:'Ensaios regionais',location:'Mara Rosa - Central',detail:'Anc.: Nilton José; Enc.: Tiago Caetano; Enc.: Wesley Ferreira'},
  {date:'2026-10-11',time:'14:00',category:'Reuniões para mocidade',location:'Mara Rosa - Central',detail:'Ancião: Nilton José'},
  {date:'2026-10-18',time:'09:00',category:'Ensaios regionais',location:'Rubiataba - Central',detail:'Anc.: Moisés Eduardo; Enc.: Edvaldo Pereira; Enc.: Manoel Messias'},
  {date:'2026-10-18',time:'14:00',category:'Reuniões para mocidade',location:'Rubiataba - Central',detail:'Ancião: Moisés Eduardo'}
];
